version: "3.8"
services:
  postgresdb:
    image : postgres
    container_name: emlo_db
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=mysecretpassword
    - POSTGRES_DB=postgres
    volumes:
    - ./data:/var/lib/postgresql/data/
    - ./temp:/temp
    ports:
    - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: emlo_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=name@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    links:
      - postgresdb