version: "3.8"
services:
  uploader:
    build : .
    env_file:
      - db.env
    volumes:
      - ./src:/usr/src/app
    depends_on:
      - "rabbitmq"
      - "postgres"
  rabbitmq:
    image: rabbitmq:3-alpine
    ports:
      - 5672:5672
  postgres:
    build : database/.
    container_name: emlo_db
    env_file:
      - db.env
    volumes:
    - ./data:/var/lib/postgresql/data/
    ports:
    - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: emlo_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=name@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    links:
      - postgres
    depends_on:
      - "postgres"